/*
*   命令码的定义
*/

#define CMD_CLIENT2GATE 100

#define CMD_GAME2CLIENT 200

#define CMD_GATE2GAME   300

enum{
	CMD_INVAILD = 0,
	CMD_PLY_CONNECTING,//用户请求建立连接
	CMD_GAME_BUSY,     //通知玩家系统繁忙
	CMD_PLY_LOGIN = CMD_CLIENT2GATE,
	CMD_PLY_LOGOUT,    //玩家主动登出
	CMD_PLY_CREATE_ACCOUNT,//创建账号
	CMD_PLY_CREATE_CHARACTER,
	CMD_CLIENT2GATE_END,
	CMD_GAME2CLIENT_END,
	CMD_PLY_DISCONNECT = CMD_GATE2GAME,
	CMD_GATE2GAME_END,
};
